import { createHash } from 'node:crypto';

/**
 * Builds the whole seeded store as plain objects. No database, no clock, no
 * randomness that is not seeded - call it twice with the same anchor and you
 * get two deeply equal results, which is what makes FR-25 testable without
 * touching MongoDB.
 *
 * Ids are derived from a hash of each document's natural key rather than
 * generated by MongoDB, so re-seeding overwrites the same documents instead
 * of creating a second store.
 */

export type Id = string;

const DAY = 24 * 60 * 60 * 1000;

/** A 24-hex ObjectId derived from a stable key. */
export function idOf(key: string): Id {
  return createHash('sha1').update(key).digest('hex').slice(0, 24);
}

/** mulberry32: small, fast, and seeded, so the "random" choices repeat exactly. */
function rng(seed: number): () => number {
  let a = seed;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export interface SeedAsset {
  _id: Id;
  code: string;
  name: string;
  kind: string;
  requiredCertification: string | null;
  addedToStoreAt: Date;
}

export interface SeedWorker {
  _id: Id;
  employeeNo: string;
  name: string;
  active: boolean;
  certifications: { code: string; issuedAt: Date; expiresAt: Date }[];
}

export interface SeedKeeper {
  _id: Id;
  name: string;
}

export interface SeedMovement {
  _id: Id;
  assetId: Id;
  type: 'ISSUE' | 'RETURN' | 'OUT_OF_SERVICE' | 'BACK_IN_SERVICE';
  occurredAt: Date;
  recordedAt: Date;
  keeperId: Id;
  workerId: Id | null;
  returnedByWorkerId: Id | null;
  dueAt: Date | null;
  condition: 'OK' | 'DAMAGED' | null;
  reservationId: Id | null;
  correctsMovementId: Id | null;
  correctionReason: string | null;
  reason: string | null;
  note: string | null;
  idempotencyKey: string | null;
}

export interface SeedReservation {
  _id: Id;
  assetId: Id;
  workerId: Id;
  keeperId: Id;
  startsAt: Date;
  endsAt: Date;
  status: 'PENDING' | 'COLLECTED' | 'CANCELLED';
  collectedMovementId: Id | null;
  cancelledAt: Date | null;
  cancelReason: string | null;
  idempotencyKey: string | null;
}

export interface SeedHolding {
  _id: Id;
  state: 'ACTIVE';
  workerId: Id;
  issueMovementId: Id;
  since: Date;
  dueAt: Date | null;
  intent: null;
  claimedAt: Date;
  idempotencyKey: string | null;
}

export interface SeededStore {
  anchor: Date;
  assets: SeedAsset[];
  workers: SeedWorker[];
  keepers: SeedKeeper[];
  movements: SeedMovement[];
  reservations: SeedReservation[];
  holdings: SeedHolding[];
}

const CERT_HEIGHT = 'WORKING_AT_HEIGHT';
const CERT_CONFINED = 'CONFINED_SPACE';
const CERT_ABRASIVE = 'ABRASIVE_WHEELS';

const KINDS = [
  { kind: 'harness', prefix: 'HARN', count: 10, cert: CERT_HEIGHT, name: 'Fall-arrest harness' },
  { kind: 'gas detector', prefix: 'GAS', count: 8, cert: CERT_CONFINED, name: 'Four-gas detector' },
  { kind: 'angle grinder', prefix: 'GRIN', count: 8, cert: CERT_ABRASIVE, name: '115mm angle grinder' },
  { kind: 'drill', prefix: 'DRIL', count: 12, cert: null, name: 'SDS hammer drill' },
  { kind: 'ladder', prefix: 'LADD', count: 10, cert: null, name: 'Fibreglass step ladder' },
  { kind: 'generator', prefix: 'GEN', count: 6, cert: null, name: '2kVA petrol generator' },
  { kind: 'scaffold tower', prefix: 'SCAF', count: 6, cert: null, name: 'Alloy tower section' },
];

const WORKER_NAMES = [
  'Amir Shah',
  'Bilal Haque',
  'Carla Mendes',
  'Danish Iqbal',
  'Eve Osei',
  'Farid Karim',
  'Grace Whelan',
  'Hamza Yusuf',
  'Ingrid Sollis',
  'Jamal Rahman',
  'Katya Petrova',
  'Liam Doyle',
];

const KEEPER_NAMES = ['Nadia Aslam', 'Owen Pryce', 'Priya Nair'];

/** Midnight UTC of the day the anchor falls on, so the store has clean edges. */
function startOfDay(date: Date): Date {
  const d = new Date(date);
  d.setUTCHours(0, 0, 0, 0);
  return d;
}

function at(base: Date, days: number, hours = 0, minutes = 0): Date {
  return new Date(base.getTime() + days * DAY + hours * 3600_000 + minutes * 60_000);
}

export function buildSeed(anchorInput: Date): SeededStore {
  const anchor = startOfDay(anchorInput);
  const windowStart = at(anchor, -30);
  const random = rng(0x5eed);

  // ---- assets -------------------------------------------------------------
  const assets: SeedAsset[] = [];
  for (const spec of KINDS) {
    for (let n = 1; n <= spec.count; n += 1) {
      const code = `${spec.prefix}-${String(n).padStart(3, '0')}`;
      assets.push({
        _id: idOf(`asset:${code}`),
        code,
        name: `${spec.name} ${code}`,
        kind: spec.kind,
        requiredCertification: spec.cert,
        // Most assets predate the window. Two arrive inside it, so "as of"
        // before their arrival has something real to report.
        addedToStoreAt: n === spec.count && spec.prefix === 'DRIL' ? at(anchor, -12) : at(anchor, -120),
      });
    }
  }

  const assetOf = (code: string) => assets.find((a) => a.code === code)!;

  // ---- workers ------------------------------------------------------------
  const workers: SeedWorker[] = WORKER_NAMES.map((name, i) => {
    const employeeNo = `E${String(1001 + i)}`;
    const certifications: SeedWorker['certifications'] = [];

    // Heights: most of the crew. Worker 3's expired a week before the anchor,
    // which is the refusal the assessor is told to try (FR-22).
    if (i % 2 === 0 || i === 3) {
      certifications.push({
        code: CERT_HEIGHT,
        issuedAt: at(anchor, -700),
        expiresAt: i === 3 ? at(anchor, -7) : at(anchor, 300),
      });
    }
    // Worker 7's confined-space ticket expires inside the seeded window, so
    // the expiry warning on the workers page has something to show.
    if (i % 3 === 0 || i === 7) {
      certifications.push({
        code: CERT_CONFINED,
        issuedAt: at(anchor, -500),
        expiresAt: i === 7 ? at(anchor, 9) : at(anchor, 250),
      });
    }
    if (i % 4 === 1) {
      certifications.push({
        code: CERT_ABRASIVE,
        issuedAt: at(anchor, -400),
        expiresAt: at(anchor, 400),
      });
    }

    return {
      _id: idOf(`worker:${employeeNo}`),
      employeeNo,
      name,
      active: true,
      certifications,
    };
  });

  const keepers: SeedKeeper[] = KEEPER_NAMES.map((name) => ({
    _id: idOf(`keeper:${name}`),
    name,
  }));

  const keeperAt = (n: number) => keepers[n % keepers.length]._id;

  /** Whether a worker's certificate covers this instant, expiry inclusive to end of day. */
  const certified = (worker: SeedWorker, code: string | null, when: Date): boolean => {
    if (!code) return true;
    return worker.certifications.some((c) => {
      const end = new Date(c.expiresAt);
      end.setUTCHours(23, 59, 59, 999);
      return c.code === code && c.issuedAt <= when && when <= end;
    });
  };

  // ---- the 30 days --------------------------------------------------------
  const movements: SeedMovement[] = [];
  const held = new Map<Id, { workerId: Id; since: Date; dueAt: Date; movementId: Id }>();
  const outOfService = new Set<Id>();
  let seq = 0;

  const push = (m: Omit<SeedMovement, '_id'> & { key?: string }): SeedMovement => {
    seq += 1;
    const { key, ...rest } = m;
    const movement: SeedMovement = { _id: idOf(`movement:${key ?? seq}`), ...rest };
    movements.push(movement);
    return movement;
  };

  const issue = (asset: SeedAsset, worker: SeedWorker, when: Date, dueInDays: number, key?: string) => {
    const dueAt = at(when, dueInDays);
    const m = push({
      key,
      assetId: asset._id,
      type: 'ISSUE',
      occurredAt: when,
      recordedAt: when,
      keeperId: keeperAt(seq),
      workerId: worker._id,
      returnedByWorkerId: null,
      dueAt,
      condition: null,
      reservationId: null,
      correctsMovementId: null,
      correctionReason: null,
      reason: null,
      note: null,
      idempotencyKey: null,
    });
    held.set(asset._id, { workerId: worker._id, since: when, dueAt, movementId: m._id });
    return m;
  };

  const giveBack = (
    asset: SeedAsset,
    when: Date,
    options: { by?: Id; condition?: 'OK' | 'DAMAGED'; note?: string; key?: string } = {},
  ) => {
    const current = held.get(asset._id);
    if (!current) return;
    push({
      key: options.key,
      assetId: asset._id,
      type: 'RETURN',
      occurredAt: when,
      recordedAt: when,
      keeperId: keeperAt(seq),
      workerId: null,
      returnedByWorkerId: options.by ?? current.workerId,
      dueAt: null,
      condition: options.condition ?? 'OK',
      reservationId: null,
      correctsMovementId: null,
      correctionReason: null,
      reason: null,
      note: options.note ?? null,
      idempotencyKey: null,
    });
    held.delete(asset._id);
  };

  /**
   * These assets tell the specific stories the spec asks to see, further down.
   * The random traffic below must not touch them: those stories write into the
   * middle of the window, and a random issue on the same asset would leave a
   * timeline where a return precedes its issue.
   */
  const SCRIPTED = new Set([
    'LADD-009', // out of service, still out
    'GRIN-004', // damaged return, later repaired
    'DRIL-003', // returned by someone other than the holder
    'GEN-002', // late entry
    'HARN-002', // correction
    'SCAF-002', // overdue
    'GAS-006', // overdue
  ]);

  // Ordinary traffic: a handful out each morning, most back within a day or
  // two. The simulation tracks who holds what so the ledger it produces is
  // one the fold accepts - no asset is ever issued twice over.
  for (let day = 0; day < 30; day += 1) {
    const morning = at(windowStart, day, 7, 30);

    for (const [assetId, current] of [...held]) {
      const daysOut = (morning.getTime() - current.since.getTime()) / DAY;
      if (daysOut >= 1 && random() < 0.75) {
        const asset = assets.find((a) => a._id === assetId)!;
        // Handed back before the hatch opens, so a tool returned this morning
        // can go out again the same morning without the re-issue landing
        // earlier on the clock than the return that freed it.
        giveBack(asset, at(morning, 0, -1, Math.floor(random() * 50)));
      }
    }

    const issuesToday = 3 + Math.floor(random() * 4);
    for (let n = 0; n < issuesToday; n += 1) {
      const asset = assets[Math.floor(random() * assets.length)];
      if (SCRIPTED.has(asset.code) || held.has(asset._id) || outOfService.has(asset._id)) continue;

      const when = at(morning, 0, 0, n * 12);
      const eligible = workers.filter((w) => certified(w, asset.requiredCertification, when));
      if (eligible.length === 0) continue;

      issue(asset, eligible[Math.floor(random() * eligible.length)], when, 1 + Math.floor(random() * 3));
    }
  }

  // ---- the specific facts the spec asks for -------------------------------

  // One asset out of service and still out (FR-21).
  const brokenLadder = assetOf('LADD-009');
  outOfService.add(brokenLadder._id);
  push({
    key: 'oos-ladder',
    assetId: brokenLadder._id,
    type: 'OUT_OF_SERVICE',
    occurredAt: at(anchor, -9, 16),
    recordedAt: at(anchor, -9, 16),
    keeperId: keeperAt(1),
    workerId: null,
    returnedByWorkerId: null,
    dueAt: null,
    condition: null,
    reservationId: null,
    correctsMovementId: null,
    correctionReason: null,
    reason: 'Cracked stile found during weekly inspection.',
    note: null,
    idempotencyKey: null,
  });

  // A damaged return: two movements at the same instant, then repaired.
  const damagedGrinder = assetOf('GRIN-004');
  const fitter = workers.find((w) => certified(w, CERT_ABRASIVE, at(anchor, -14)))!;
  issue(damagedGrinder, fitter, at(anchor, -14, 8), 1, 'grinder-issue');
  const damagedAt = at(anchor, -13, 16, 20);
  giveBack(damagedGrinder, damagedAt, { condition: 'DAMAGED', note: 'Guard sheared off.', key: 'grinder-return' });
  push({
    key: 'grinder-oos',
    assetId: damagedGrinder._id,
    type: 'OUT_OF_SERVICE',
    occurredAt: damagedAt,
    recordedAt: damagedAt,
    keeperId: keeperAt(2),
    workerId: null,
    returnedByWorkerId: null,
    dueAt: null,
    condition: null,
    reservationId: null,
    correctsMovementId: null,
    correctionReason: null,
    reason: 'Returned damaged: guard sheared off.',
    note: null,
    idempotencyKey: null,
  });
  push({
    key: 'grinder-bis',
    assetId: damagedGrinder._id,
    type: 'BACK_IN_SERVICE',
    occurredAt: at(anchor, -6, 11),
    recordedAt: at(anchor, -6, 11),
    keeperId: keeperAt(0),
    workerId: null,
    returnedByWorkerId: null,
    dueAt: null,
    condition: null,
    reservationId: null,
    correctsMovementId: null,
    correctionReason: null,
    reason: null,
    note: 'New guard fitted.',
    idempotencyKey: null,
  });

  // A return handed in by someone other than the holder (FR-4).
  const sharedDrill = assetOf('DRIL-003');
  issue(sharedDrill, workers[2], at(anchor, -8, 8), 1, 'shared-issue');
  giveBack(sharedDrill, at(anchor, -7, 16, 10), {
    by: workers[9]._id,
    note: 'Handed in by a colleague at the end of the shift.',
    key: 'shared-return',
  });

  // A late entry: it happened six days ago, it was written today (FR-17).
  const lateGenerator = assetOf('GEN-002');
  const lateIssue = push({
    key: 'late-issue',
    assetId: lateGenerator._id,
    type: 'ISSUE',
    occurredAt: at(anchor, -6, 6, 45),
    recordedAt: at(anchor, 0, 9, 5),
    keeperId: keeperAt(2),
    workerId: workers[4]._id,
    returnedByWorkerId: null,
    dueAt: at(anchor, -4, 17),
    condition: null,
    reservationId: null,
    correctsMovementId: null,
    correctionReason: null,
    reason: null,
    note: 'Logged late: the book was not at the hatch that morning.',
    idempotencyKey: null,
  });
  held.set(lateGenerator._id, {
    workerId: workers[4]._id,
    since: lateIssue.occurredAt,
    dueAt: lateIssue.dueAt!,
    movementId: lateIssue._id,
  });

  // A correction: the wrong worker was picked from the list (FR-18).
  const misloggedHarness = assetOf('HARN-002');
  const wrongIssue = push({
    key: 'mislogged-issue',
    assetId: misloggedHarness._id,
    type: 'ISSUE',
    occurredAt: at(anchor, -10, 7, 40),
    recordedAt: at(anchor, -10, 7, 40),
    keeperId: keeperAt(0),
    workerId: workers[0]._id,
    returnedByWorkerId: null,
    dueAt: at(anchor, -10, 17),
    condition: null,
    reservationId: null,
    correctsMovementId: null,
    correctionReason: null,
    reason: null,
    note: null,
    idempotencyKey: null,
  });
  push({
    key: 'mislogged-correction',
    assetId: misloggedHarness._id,
    type: 'ISSUE',
    occurredAt: wrongIssue.occurredAt,
    recordedAt: at(anchor, -9, 10, 15),
    keeperId: keeperAt(1),
    workerId: workers[8]._id,
    returnedByWorkerId: null,
    dueAt: wrongIssue.dueAt,
    condition: null,
    reservationId: null,
    correctsMovementId: wrongIssue._id,
    correctionReason: 'Wrong name picked from the list: Ingrid took it, not Amir.',
    reason: null,
    note: null,
    idempotencyKey: null,
  });
  push({
    key: 'mislogged-return',
    assetId: misloggedHarness._id,
    type: 'RETURN',
    occurredAt: at(anchor, -10, 16, 50),
    recordedAt: at(anchor, -10, 16, 50),
    keeperId: keeperAt(1),
    workerId: null,
    returnedByWorkerId: workers[8]._id,
    dueAt: null,
    condition: 'OK',
    reservationId: null,
    correctsMovementId: null,
    correctionReason: null,
    reason: null,
    note: null,
    idempotencyKey: null,
  });

  // Two overdue holdings, so the board has something red on it (FR-23).
  for (const [code, workerIndex, daysAgo] of [
    ['SCAF-002', 5, 4],
    ['GAS-006', 6, 6],
  ] as const) {
    const asset = assetOf(code);
    if (held.has(asset._id)) giveBack(asset, at(anchor, -daysAgo - 1, 16));
    if (outOfService.has(asset._id)) continue;
    const worker = workers[workerIndex];
    if (!certified(worker, asset.requiredCertification, at(anchor, -daysAgo))) continue;
    issue(asset, worker, at(anchor, -daysAgo, 7, 15), 1, `overdue-${code}`);
  }

  // ---- reservations -------------------------------------------------------
  const reservations: SeedReservation[] = [];
  const reserve = (
    key: string,
    code: string,
    workerIndex: number,
    startDays: number,
    endDays: number,
    status: SeedReservation['status'],
    extra: Partial<SeedReservation> = {},
  ) => {
    reservations.push({
      _id: idOf(`reservation:${key}`),
      assetId: assetOf(code)._id,
      workerId: workers[workerIndex]._id,
      keeperId: keeperAt(workerIndex),
      startsAt: at(anchor, startDays, 8),
      endsAt: at(anchor, endDays, 17),
      status,
      collectedMovementId: null,
      cancelledAt: null,
      cancelReason: null,
      idempotencyKey: null,
      ...extra,
    });
  };

  reserve('past-collected', 'DRIL-006', 2, -5, -5, 'COLLECTED');
  // Booked, never turned up: derived from PENDING with a window in the past
  // rather than stored as a status (FR-24).
  reserve('never-collected', 'LADD-004', 10, -3, -3, 'PENDING');
  reserve('future-a', 'GEN-001', 4, 2, 3, 'PENDING');
  reserve('future-b', 'SCAF-005', 8, 3, 4, 'PENDING');
  // Adjacent to future-b, sharing an edge, which is allowed and worth seeing.
  reserve('future-c', 'SCAF-005', 1, 4, 5, 'PENDING');
  reserve('future-cancelled', 'DRIL-001', 11, 6, 7, 'CANCELLED', {
    cancelledAt: at(anchor, -1, 12),
    cancelReason: 'Job moved to next month.',
  });

  // ---- the holding guard --------------------------------------------------
  // One document per asset still out. Without these the ledger and the guard
  // would disagree and the invariant checker would rightly fail.
  const holdings: SeedHolding[] = [...held.entries()].map(([assetId, current]) => ({
    _id: assetId,
    state: 'ACTIVE',
    workerId: current.workerId,
    issueMovementId: current.movementId,
    since: current.since,
    dueAt: current.dueAt,
    intent: null,
    claimedAt: current.since,
    idempotencyKey: null,
  }));

  movements.sort((a, b) =>
    a.occurredAt.getTime() - b.occurredAt.getTime() ||
    a.recordedAt.getTime() - b.recordedAt.getTime() ||
    (a._id < b._id ? -1 : a._id > b._id ? 1 : 0),
  );

  return { anchor, assets, workers, keepers, movements, reservations, holdings };
}
