import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { SchemaTypes } from 'mongoose';
import type { HydratedDocument, Types } from 'mongoose';
import type { MovementType, ReturnCondition } from '../../domain/types.js';

/**
 * The ledger. Append-only: nothing in the application ever updates or deletes
 * a movement. A mistake is fixed by writing a correction that points at it,
 * so the original stays visible (FR-18).
 *
 * `_id` is generated by the writer before the document is inserted, not by
 * MongoDB. That is what makes replaying an interrupted write idempotent -
 * the second insert collides on `_id` instead of creating a twin (PLAN.md §7).
 */
@Schema({ collection: 'movements', timestamps: { createdAt: false, updatedAt: false } })
export class Movement {
  @Prop({ type: SchemaTypes.ObjectId, ref: 'Asset', required: true })
  assetId: Types.ObjectId;

  @Prop({
    type: String,
    required: true,
    enum: ['ISSUE', 'RETURN', 'OUT_OF_SERVICE', 'BACK_IN_SERVICE'],
  })
  type: MovementType;

  /** When it actually happened. May be backdated; never in the future. */
  @Prop({ required: true })
  occurredAt: Date;

  /** When it was written. Always the server clock, never the client's. */
  @Prop({ required: true })
  recordedAt: Date;

  @Prop({ type: SchemaTypes.ObjectId, ref: 'Keeper', required: true })
  keeperId: Types.ObjectId;

  /** The holder, on ISSUE. */
  @Prop({ type: SchemaTypes.ObjectId, ref: 'Worker', default: null })
  workerId: Types.ObjectId | null;

  /** Who physically handed it back, on RETURN. May differ from the holder (FR-4). */
  @Prop({ type: SchemaTypes.ObjectId, ref: 'Worker', default: null })
  returnedByWorkerId: Types.ObjectId | null;

  @Prop({ type: Date, default: null })
  dueAt: Date | null;

  @Prop({ type: String, enum: ['OK', 'DAMAGED'], default: null })
  condition: ReturnCondition | null;

  @Prop({ type: SchemaTypes.ObjectId, ref: 'Reservation', default: null })
  reservationId: Types.ObjectId | null;

  /** Set on a correction: the movement this one supersedes. */
  @Prop({ type: SchemaTypes.ObjectId, ref: 'Movement', default: null })
  correctsMovementId: Types.ObjectId | null;

  @Prop({ type: String, default: null })
  correctionReason: string | null;

  @Prop({ type: String, default: null })
  reason: string | null;

  @Prop({ type: String, default: null })
  note: string | null;

  /**
   * Which request wrote this. Deliberately NOT unique: a damaged return
   * writes a RETURN and an OUT_OF_SERVICE under one key. Deduplication is
   * the pre-generated `_id`'s job, and replay is the idempotency_keys
   * collection's job.
   */
  @Prop({ type: String, default: null })
  idempotencyKey: string | null;
}

export type MovementDocument = HydratedDocument<Movement>;
export const MovementSchema = SchemaFactory.createForClass(Movement);

// The fold reads one asset's whole life in occurredAt order; this index is
// what keeps that a range scan rather than a collection scan.
MovementSchema.index({ assetId: 1, occurredAt: 1 });
MovementSchema.index({ occurredAt: -1 });
MovementSchema.index({ recordedAt: -1 });
MovementSchema.index({ workerId: 1, occurredAt: -1 });
MovementSchema.index({ correctsMovementId: 1 }, { sparse: true });
MovementSchema.index({ idempotencyKey: 1 }, { sparse: true });
